import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import { NavbarMenu } from "@/components/Navbar"
import { Card, CardDescription } from "@/components/ui/card"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<NavbarMenu />
			<body className="max-w-7xl m-auto pt-40">
				<main>{children}</main>

				<Card>
					<CardDescription className="container mx-auto px-6 py-4">
						<div className="flex justify-between">
							<div>
								<p className="font-bold text-lg">Mövenpick Resort Kuredhivaru Maldives</p>
								<p className="mt-2 text-sm">© {new Date().getFullYear()} Hung Nguyen</p>

								<Link href="/privacy">
									<p className="text-sm hover:underline">Privacy Policy</p>
								</Link>
								<Link href="/terms">
									<p className="text-sm hover:underline">Terms of Service</p>
								</Link>
							</div>
						</div>
					</CardDescription>
				</Card>
			</body>
		</html>
	)
}
