import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import Navbar from "@/components/Navbar"
import { Card, CardDescription } from "@/components/ui/card"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} max-w-6xl m-auto`}>
				<div className="sticky top-0 z-50 bg-white shadow-sm">
					<div className="flex justify-center">
						<Navbar />
					</div>
				</div>

				{/* Main Content */}
				<div className="pt-16">
					<main>{children}</main>
				</div>

				{/* Footer */}
				<Card>
					<div className="flex items-center justify-between">
						<CardDescription className="container px-6  m-auto text-center py-4">
							Mövenpick Resort Kuredhivaru Maldives <br /> © {new Date().getFullYear()} Hung Nguyen <br />
							<Link href="/privacy">Privacy Policy</Link> <br />
							<Link href="/terms">Terms of Service</Link>
						</CardDescription>
					</div>
				</Card>
			</body>
		</html>
	)
}
